# Generated by Django 4.1.5 on 2023-01-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                        ],
                        max_length=40,
                    ),
                ),
                ("creation_date", models.DateField(auto_now=True)),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
                ("current_streak", models.IntegerField()),
                ("max_streak", models.IntegerField()),
                ("break_streak", models.IntegerField()),
                ("completed", models.BooleanField(default=False)),
            ],
            options={"db_table": "habit",},
        ),
        migrations.CreateModel(
            name="ModelTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskcomplete", models.BooleanField(default=False)),
                ("task_date", models.DateField()),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit_tracker.modelhabit",
                    ),
                ),
            ],
            options={"db_table": "task",},
        ),
    ]
