# Generated by Django 4.1.5 on 2023-02-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_remove_modelhabit_break_streak_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelhabit",
            name="current_streak",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="modelhabit",
            name="max_streak",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="modelhabit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("DAILY", "DAILY"),
                    ("WEEKLY", "WEEKLY"),
                    ("MONTHLY", "MONTHLY"),
                ],
                default="DAILY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="modelhabit",
            name="worst_streak",
            field=models.IntegerField(default="0"),
        ),
        migrations.AlterField(
            model_name="modeltask",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_task",
                to="habit_tracker.modelhabit",
            ),
        ),
    ]
